[package]
name = "wasmmod-read"
version = "0.1.4-alpha"
edition = "2021"
license = "MIT"
description = "Standalone reader for wasmmod.pack / wasmmod.source custom sections"
repository = "https://github.com/pymergetic/wasmmod"
readme = "README.md"

[[bin]]
name = "wasmmod-read"
path = "src/bin/wasmmod-read.rs"

[dependencies]
flate2 = { version = "1", default-features = true, features = ["rust_backend"] }
thiserror = "2"

[dev-dependencies]
