/* DO NOT EDIT — generated by `pymergetic.util.gen` (live registry introspection).
 * Source of truth: pm_wasmmod_registry_* after PM_MOD_EXPORT_* / PM_MOD_EXPORT_RS! registration.
 */
#ifndef PYMERGETIC_WASMMOD_IO_EXPORT_H
#define PYMERGETIC_WASMMOD_IO_EXPORT_H

#include <stddef.h>
#include <stdint.h>

#include "pymergetic/wasmmod/io/__types__.h"

#ifdef __cplusplus
extern "C" {
#endif

void pm_wasmmod_io_set(const pm_wasmmod_io_ops_t *);

const pm_wasmmod_io_ops_t * pm_wasmmod_io_get(void);

void pm_wasmmod_io_yield(void);

int32_t pm_wasmmod_io_uri_is_http(const char *);

void pm_wasmmod_io_join_uri(const char *, const char *, char *, uint32_t);

void pm_wasmmod_io_set_auth_bearer(const char *);

const char * pm_wasmmod_io_auth_bearer(void);

int32_t pm_wasmmod_io_fetch(const char *, uint8_t **, uint32_t *, char *, size_t);

int32_t pm_wasmmod_io_probe(const char *);

int32_t pm_wasmmod_io_request(const char *, const char *, const uint8_t *, uint32_t, const char *, uint8_t **, uint32_t *, char *, size_t);

#ifdef __cplusplus
}
#endif

#endif /* PYMERGETIC_WASMMOD_IO_EXPORT_H */
