//! DO NOT EDIT — generated by `pymergetic.util.gen` (live registry introspection).

#![allow(non_camel_case_types)]

#[repr(C)]
pub struct pm_wasmmod_io_ops_t {
    _opaque: [u8; 0],
}

unsafe extern "C" {
    pub fn pm_wasmmod_io_set(a0: *const pm_wasmmod_io_ops_t);
    pub fn pm_wasmmod_io_get() -> *const pm_wasmmod_io_ops_t;
    pub fn pm_wasmmod_io_yield();
    pub fn pm_wasmmod_io_uri_is_http(a0: *const u8) -> i32;
    pub fn pm_wasmmod_io_join_uri(a0: *const u8, a1: *const u8, a2: *mut u8, a3: u32);
    pub fn pm_wasmmod_io_set_auth_bearer(a0: *const u8);
    pub fn pm_wasmmod_io_auth_bearer() -> *const u8;
    pub fn pm_wasmmod_io_fetch(a0: *const u8, a1: *mut *mut u8, a2: *mut u32, a3: *mut u8, a4: usize) -> i32;
    pub fn pm_wasmmod_io_probe(a0: *const u8) -> i32;
    pub fn pm_wasmmod_io_request(a0: *const u8, a1: *const u8, a2: *const u8, a3: u32, a4: *const u8, a5: *mut *mut u8, a6: *mut u32, a7: *mut u8, a8: usize) -> i32;
}
