# DO NOT EDIT — generated by `pymergetic.util.gen` (live µPy import).
# pymergetic.util.version

from typing import Any

def cmp(*args: Any, **kwargs: Any) -> Any: ...

def satisfies(*args: Any, **kwargs: Any) -> Any: ...

