/*
 * pymergetic.util.gen µPy face + optional wasmmod.gen alias.
 * Gated by MICROPY_PY_WASM_GEN.
 */

#include "ports/micropython/mpconfig_wasm.h"

#ifndef MICROPY_PY_WASM_GEN
#define MICROPY_PY_WASM_GEN (0)
#endif

#if MICROPY_PY_WASM_GEN

#include <string.h>

#include "extmod/vfs.h"
#include "py/obj.h"
#include "py/objmodule.h"
#include "py/runtime.h"
#include "py/stream.h"

#include "ports/micropython/importhook.h"
#include "ports/micropython/modgen.h"
#include "pymergetic/util/gen/__exports__.h"

static vstr_t gen_pyi_buf;
static int gen_pyi_buf_inited;

static int32_t gen_py_face_provider(void *ctx, const uint8_t *fqn, uint32_t fqn_len,
    uint8_t *buf, uint32_t *inout_len) {
    (void)ctx;
    if (fqn == NULL || fqn_len == 0 || inout_len == NULL) {
        return -1;
    }
    if (!gen_pyi_buf_inited) {
        vstr_init(&gen_pyi_buf, 256);
        gen_pyi_buf_inited = 1;
    }
    if (buf == NULL) {
        vstr_reset(&gen_pyi_buf);
        nlr_buf_t nlr;
        if (nlr_push(&nlr) != 0) {
            return 0;
        }
        qstr q = qstr_from_strn((const char *)fqn, fqn_len);
        mp_obj_t mod = mp_import_name(q, mp_const_empty_tuple, MP_OBJ_NEW_SMALL_INT(0));
        mp_obj_dict_t *globals = mp_obj_module_get_globals(mod);
        if (globals == NULL) {
            nlr_pop();
            return 0;
        }
        vstr_add_str(&gen_pyi_buf, "# DO NOT EDIT — generated by `pymergetic.util.gen` (live µPy import).\n# ");
        vstr_add_strn(&gen_pyi_buf, (const char *)fqn, fqn_len);
        vstr_add_str(&gen_pyi_buf, "\n\nfrom typing import Any\n\n");
        int any = 0;
        mp_map_t *map = &globals->map;
        for (size_t i = 0; i < map->alloc; ++i) {
            if (!mp_map_slot_is_filled(map, i) || !mp_obj_is_qstr(map->table[i].key)) {
                continue;
            }
            const char *name = qstr_str(MP_OBJ_QSTR_VALUE(map->table[i].key));
            if (name[0] == '_') {
                continue;
            }
            if (!mp_obj_is_callable(map->table[i].value)) {
                continue;
            }
            vstr_add_str(&gen_pyi_buf, "def ");
            vstr_add_str(&gen_pyi_buf, name);
            vstr_add_str(&gen_pyi_buf, "(*args: Any, **kwargs: Any) -> Any: ...\n\n");
            any = 1;
        }
        nlr_pop();
        if (!any) {
            return 0;
        }
        *inout_len = (uint32_t)gen_pyi_buf.len;
        return 1;
    }
    uint32_t n = *inout_len;
    if (n > gen_pyi_buf.len) {
        n = (uint32_t)gen_pyi_buf.len;
    }
    memcpy(buf, gen_pyi_buf.buf, n);
    *inout_len = n;
    return 1;
}

static int32_t gen_vfs_read(void *ctx, const uint8_t *path, uint32_t path_len,
    uint8_t *buf, uint32_t *inout_len) {
    (void)ctx;
    if (path == NULL || path_len == 0 || inout_len == NULL) {
        return -1;
    }
    nlr_buf_t nlr;
    if (nlr_push(&nlr) != 0) {
        return 0;
    }
    mp_obj_t path_obj = mp_obj_new_str((const char *)path, path_len);
    mp_obj_t mode = mp_obj_new_str("rb", 2);
    mp_obj_t open_args[2] = { path_obj, mode };
    mp_obj_t f = mp_vfs_open(2, open_args, (mp_map_t *)&mp_const_empty_map);
    const mp_stream_p_t *stream = mp_get_stream_raise(f, MP_STREAM_OP_READ);
    vstr_t data;
    vstr_init(&data, 256);
    uint8_t chunk[512];
    for (;;) {
        int err = 0;
        mp_uint_t n = stream->read(f, chunk, sizeof(chunk), &err);
        if (n == MP_STREAM_ERROR) {
            vstr_clear(&data);
            mp_stream_close(f);
            nlr_pop();
            return -1;
        }
        if (n == 0) {
            break;
        }
        vstr_add_strn(&data, (const char *)chunk, n);
    }
    mp_stream_close(f);
    nlr_pop();
    if (buf == NULL) {
        *inout_len = (uint32_t)data.len;
        vstr_clear(&data);
        return 1;
    }
    uint32_t n = *inout_len;
    if (n > data.len) {
        n = (uint32_t)data.len;
    }
    memcpy(buf, data.buf, n);
    *inout_len = n;
    vstr_clear(&data);
    return 1;
}

static int32_t gen_vfs_write(void *ctx, const uint8_t *path, uint32_t path_len,
    const uint8_t *data, uint32_t data_len) {
    (void)ctx;
    if (path == NULL || path_len == 0) {
        return -1;
    }
    nlr_buf_t nlr;
    if (nlr_push(&nlr) != 0) {
        return -1;
    }
    mp_obj_t path_obj = mp_obj_new_str((const char *)path, path_len);
    mp_obj_t mode = mp_obj_new_str("wb", 2);
    mp_obj_t open_args[2] = { path_obj, mode };
    mp_obj_t f = mp_vfs_open(2, open_args, (mp_map_t *)&mp_const_empty_map);
    const mp_stream_p_t *stream = mp_get_stream_raise(f, MP_STREAM_OP_WRITE);
    int err = 0;
    mp_uint_t n = stream->write(f, data, data_len, &err);
    mp_stream_close(f);
    nlr_pop();
    if (n == MP_STREAM_ERROR || n != data_len) {
        return -1;
    }
    return 0;
}

static void gen_install_py_face(void) {
    pm_util_gen_set_py_face_provider(gen_py_face_provider, NULL);
}

static mp_obj_t mod_wasm_gen(size_t n_args, const mp_obj_t *args) {
    mp_wasm_ensure_inited();
    gen_install_py_face();
    const char *root = ".";
    int check = 0;
    if (n_args >= 1 && args[0] != mp_const_none) {
        root = mp_obj_str_get_str(args[0]);
    }
    if (n_args >= 2) {
        check = mp_obj_is_true(args[1]);
    }
    int32_t rc = pm_util_gen_run((const uint8_t *)root, (uint32_t)strlen(root), check);
    return MP_OBJ_NEW_SMALL_INT(rc);
}
MP_DEFINE_CONST_FUN_OBJ_VAR_BETWEEN(mod_wasm_gen_obj, 0, 2, mod_wasm_gen);

static mp_obj_t mod_util_gen_run(size_t n_args, const mp_obj_t *args) {
    return mod_wasm_gen(n_args, args);
}
static MP_DEFINE_CONST_FUN_OBJ_VAR_BETWEEN(mod_util_gen_run_obj, 0, 2, mod_util_gen_run);

static mp_obj_t mod_util_gen_run_vfs(size_t n_args, const mp_obj_t *args) {
    mp_wasm_ensure_inited();
    gen_install_py_face();
    if (n_args < 2) {
        mp_raise_TypeError(MP_ERROR_TEXT("run_vfs needs dir and fqn"));
    }
    const char *dir = mp_obj_str_get_str(args[0]);
    const char *fqn = mp_obj_str_get_str(args[1]);
    int check = 0;
    if (n_args >= 3) {
        check = mp_obj_is_true(args[2]);
    }
    pm_util_gen_vfs_ops_t ops = { .read = gen_vfs_read, .write = gen_vfs_write };
    int32_t rc = pm_util_gen_run_vfs(
        (const uint8_t *)dir, (uint32_t)strlen(dir),
        (const uint8_t *)fqn, (uint32_t)strlen(fqn),
        check, ops, NULL);
    return MP_OBJ_NEW_SMALL_INT(rc);
}
static MP_DEFINE_CONST_FUN_OBJ_VAR_BETWEEN(mod_util_gen_run_vfs_obj, 2, 3, mod_util_gen_run_vfs);

static mp_obj_t mod_util_gen_diff(size_t n_args, const mp_obj_t *args) {
    mp_wasm_ensure_inited();
    gen_install_py_face();
    if (n_args < 1) {
        mp_raise_TypeError(MP_ERROR_TEXT("diff needs fqn"));
    }
    const char *fqn = mp_obj_str_get_str(args[0]);
    const uint8_t *h = NULL, *rs = NULL, *pyi = NULL;
    uint32_t h_len = 0, rs_len = 0, pyi_len = 0;
    size_t l;
    if (n_args >= 2 && args[1] != mp_const_none) {
        h = (const uint8_t *)mp_obj_str_get_data(args[1], &l);
        h_len = (uint32_t)l;
    }
    if (n_args >= 3 && args[2] != mp_const_none) {
        rs = (const uint8_t *)mp_obj_str_get_data(args[2], &l);
        rs_len = (uint32_t)l;
    }
    if (n_args >= 4 && args[3] != mp_const_none) {
        pyi = (const uint8_t *)mp_obj_str_get_data(args[3], &l);
        pyi_len = (uint32_t)l;
    }
    int32_t rc = pm_util_gen_diff_included(
        (const uint8_t *)fqn, (uint32_t)strlen(fqn),
        h, h_len, rs, rs_len, pyi, pyi_len);
    return MP_OBJ_NEW_SMALL_INT(rc);
}
static MP_DEFINE_CONST_FUN_OBJ_VAR_BETWEEN(mod_util_gen_diff_obj, 1, 4, mod_util_gen_diff);

static const mp_rom_map_elem_t mp_module_pymergetic_util_gen_globals_table[] = {
    { MP_ROM_QSTR(MP_QSTR___name__), MP_ROM_QSTR(MP_QSTR_pymergetic_dot_util_dot_gen) },
    { MP_ROM_QSTR(MP_QSTR_run), MP_ROM_PTR(&mod_util_gen_run_obj) },
    { MP_ROM_QSTR(MP_QSTR_run_vfs), MP_ROM_PTR(&mod_util_gen_run_vfs_obj) },
    { MP_ROM_QSTR(MP_QSTR_diff), MP_ROM_PTR(&mod_util_gen_diff_obj) },
};
static MP_DEFINE_CONST_DICT(mp_module_pymergetic_util_gen_globals, mp_module_pymergetic_util_gen_globals_table);

const mp_obj_module_t mp_module_pymergetic_util_gen = {
    .base = { &mp_type_module },
    .globals = (mp_obj_dict_t *)&mp_module_pymergetic_util_gen_globals,
};

MP_REGISTER_MODULE(MP_QSTR_pymergetic_dot_util_dot_gen, mp_module_pymergetic_util_gen);

#endif /* MICROPY_PY_WASM_GEN */
