/* DO NOT EDIT — generated by `pymergetic.util.gen` (live registry introspection).
 * Source of truth: pm_wasmmod_registry_* after PM_MOD_EXPORT_* / PM_MOD_EXPORT_RS! registration.
 */
#ifndef PYMERGETIC_UTIL_LOCK_EXPORT_H
#define PYMERGETIC_UTIL_LOCK_EXPORT_H

#include <stddef.h>
#include <stdint.h>

#include "pymergetic/util/lock/__types__.h"

#ifdef __cplusplus
extern "C" {
#endif

void pm_util_lock_acquire(pm_util_lock_t *);

void pm_util_lock_init(pm_util_lock_t *);

int32_t pm_util_lock_try_acquire(pm_util_lock_t *);

void pm_util_lock_release(pm_util_lock_t *);

#ifdef __cplusplus
}
#endif

#endif /* PYMERGETIC_UTIL_LOCK_EXPORT_H */
