/* DO NOT EDIT — generated by `wasmmod gen` (wasmmod-gen / pymergetic-wasmmod).
 * Source of truth: module muscle / provide face / type hints (see docs/SOURCETREE.md).
 */

#ifndef PYMERGETIC_UTIL_LOCK_TYPES_H
#define PYMERGETIC_UTIL_LOCK_TYPES_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef struct {
    uint32_t locked;
} pm_util_lock_t;

#ifdef __cplusplus
}
#endif

#endif /* PYMERGETIC_UTIL_LOCK_TYPES_H */
