//! DO NOT EDIT — generated by `pymergetic.util.gen` (live registry introspection).

#![allow(non_camel_case_types)]

use core::ffi::c_void;

#[repr(C)]
pub struct pm_util_mem_arena_t {
    _opaque: [u8; 0],
}

unsafe extern "C" {
    pub fn pm_util_mem_arena_create(a0: *mut c_void, a1: usize) -> *mut pm_util_mem_arena_t;
    pub fn pm_util_mem_arena_destroy(a0: *mut pm_util_mem_arena_t);
    pub fn pm_util_mem_alloc(a0: *mut pm_util_mem_arena_t, a1: usize) -> *mut c_void;
    pub fn pm_util_mem_realloc(a0: *mut pm_util_mem_arena_t, a1: *mut c_void, a2: usize) -> *mut c_void;
    pub fn pm_util_mem_memalign(a0: *mut pm_util_mem_arena_t, a1: usize, a2: usize) -> *mut c_void;
    pub fn pm_util_mem_free(a0: *mut pm_util_mem_arena_t, a1: *mut c_void);
    pub fn pm_util_mem_map(a0: *mut pm_util_mem_arena_t, a1: usize) -> *mut c_void;
    pub fn pm_util_mem_unmap(a0: *mut pm_util_mem_arena_t, a1: *mut c_void, a2: usize) -> i32;
    pub fn pm_util_mem_arena_bytes(a0: *const pm_util_mem_arena_t) -> usize;
    pub fn pm_util_mem_arena_map_used(a0: *const pm_util_mem_arena_t) -> usize;
    pub fn pm_util_mem_arena_heap_used(a0: *const pm_util_mem_arena_t) -> usize;
    pub fn pm_util_mem_arena_hole(a0: *const pm_util_mem_arena_t) -> usize;
    pub fn pm_util_mem_arena_overhead() -> usize;
}
