/* DO NOT EDIT — generated by `pymergetic.util.gen` (live registry introspection).
 * Source of truth: pm_wasmmod_registry_* after PM_MOD_EXPORT_* / PM_MOD_EXPORT_RS! registration.
 */
#ifndef PYMERGETIC_UTIL_MEM_EXPORT_H
#define PYMERGETIC_UTIL_MEM_EXPORT_H

#include <stddef.h>
#include <stdint.h>

#include "pymergetic/util/mem/__types__.h"

#ifdef __cplusplus
extern "C" {
#endif

pm_util_mem_arena_t * pm_util_mem_arena_create(void *, size_t);

void pm_util_mem_arena_destroy(pm_util_mem_arena_t *);

void * pm_util_mem_alloc(pm_util_mem_arena_t *, size_t);

void * pm_util_mem_realloc(pm_util_mem_arena_t *, void *, size_t);

void * pm_util_mem_memalign(pm_util_mem_arena_t *, size_t, size_t);

void pm_util_mem_free(pm_util_mem_arena_t *, void *);

void * pm_util_mem_map(pm_util_mem_arena_t *, size_t);

int32_t pm_util_mem_unmap(pm_util_mem_arena_t *, void *, size_t);

size_t pm_util_mem_arena_bytes(const pm_util_mem_arena_t *);

size_t pm_util_mem_arena_map_used(const pm_util_mem_arena_t *);

size_t pm_util_mem_arena_heap_used(const pm_util_mem_arena_t *);

size_t pm_util_mem_arena_hole(const pm_util_mem_arena_t *);

size_t pm_util_mem_arena_overhead(void);

#ifdef __cplusplus
}
#endif

#endif /* PYMERGETIC_UTIL_MEM_EXPORT_H */
