/* DO NOT EDIT — generated by `pymergetic.util.gen` (live registry introspection).
 * Source of truth: pm_wasmmod_registry_* after PM_MOD_EXPORT_* / PM_MOD_EXPORT_RS! registration.
 */
#ifndef PYMERGETIC_UTIL_LZ4_EXPORT_H
#define PYMERGETIC_UTIL_LZ4_EXPORT_H

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

int32_t pm_util_lz4_compress(const uint8_t *, uint32_t, uint8_t *, uint32_t);

int32_t pm_util_lz4_decompress(const uint8_t *, uint32_t, uint8_t *, uint32_t);

#ifdef __cplusplus
}
#endif

#endif /* PYMERGETIC_UTIL_LZ4_EXPORT_H */
