//! DO NOT EDIT — generated by `pymergetic.util.gen` (live registry introspection).

#![allow(non_camel_case_types)]

unsafe extern "C" {
    pub fn pm_util_lz4_compress(a0: *const u8, a1: u32, a2: *mut u8, a3: u32) -> i32;
    pub fn pm_util_lz4_decompress(a0: *const u8, a1: u32, a2: *mut u8, a3: u32) -> i32;
}
