# DO NOT EDIT — generated by `pymergetic.util.gen` (live µPy import).
# pymergetic.util.lz4

from typing import Any

def compress(*args: Any, **kwargs: Any) -> Any: ...

def decompress(*args: Any, **kwargs: Any) -> Any: ...

