//! DO NOT EDIT — generated by `pymergetic.util.gen` (live registry introspection).

#![allow(non_camel_case_types)]

unsafe extern "C" {
    pub fn pm_util_pysample_hello() -> i32;
    pub fn pm_util_pysample_echo_len(a0: *const u8, a1: u32) -> i32;
    pub fn pm_util_pysample_echo_mem(a0: i32) -> i32;
    pub fn pm_util_pysample_is_none(a0: i32) -> i32;
}
