[package]
name = "pm"
version = "0.1.0-alpha"
edition = "2021"
license = "MIT"
description = "Rust FFI bindings (bindgen) for wasmmod pm_upy / pm_wasmmod public C API"
repository = "https://github.com/pymergetic/wasmmod"
readme = "README.md"

[lib]
name = "pm"
path = "src/lib.rs"

[build-dependencies]
bindgen = "0.71"
