//! DO NOT EDIT — generated by `pymergetic.util.gen` (live registry introspection).

#![allow(non_camel_case_types)]

use core::ffi::c_void;

unsafe extern "C" {
    pub fn pm_util_zlib_inflate(a0: *const c_void, a1: usize, a2: *mut c_void, a3: usize) -> i32;
    pub fn pm_util_zlib_deflate(a0: *const c_void, a1: usize, a2: *mut c_void, a3: usize, a4: *mut c_void, a5: usize) -> i32;
}
