/* DO NOT EDIT — generated by `wasmmod gen` (wasmmod-gen / pymergetic-wasmmod).
 * Source of truth: module muscle / provide face / type hints (see docs/SOURCETREE.md).
 */

#ifndef PYMERGETIC_UTIL_ZLIB_IMPORTS_H
#define PYMERGETIC_UTIL_ZLIB_IMPORTS_H

/* Soft-connect slots — call PM_MOD_CONNECT at guest init (docs/CALLGRAPH.md). */
#include "pymergetic/wasmmod/guest.h"

/* No G→H / G→G edges declared for this module yet. */

#endif /* PYMERGETIC_UTIL_ZLIB_IMPORTS_H */
