# DO NOT EDIT — generated by `pymergetic.util.gen` (live µPy import).
# pymergetic.util.zlib

from typing import Any

def deflate(*args: Any, **kwargs: Any) -> Any: ...

def inflate(*args: Any, **kwargs: Any) -> Any: ...

