/* DO NOT EDIT — generated by `pymergetic.util.gen` (live registry introspection).
 * Source of truth: pm_wasmmod_registry_* after PM_MOD_EXPORT_* / PM_MOD_EXPORT_RS! registration.
 */
#ifndef PYMERGETIC_WASMMOD_EXAMPLES_HELLO_EXPORT_H
#define PYMERGETIC_WASMMOD_EXAMPLES_HELLO_EXPORT_H

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

int hello(void);

int add(int, int);

#ifdef __cplusplus
}
#endif

#endif /* PYMERGETIC_WASMMOD_EXAMPLES_HELLO_EXPORT_H */
