//! DO NOT EDIT — generated by `pymergetic.util.gen` (live registry introspection).

#![allow(non_camel_case_types)]

unsafe extern "C" {
    pub fn hello() -> i32;
    pub fn add(a0: i32, a1: i32) -> i32;
}
