# DO NOT EDIT — generated by `pymergetic.util.gen` (live µPy import).
# pymergetic.wasmmod_examples.hello

from typing import Any

def add(*args: Any, **kwargs: Any) -> Any: ...

def hello(*args: Any, **kwargs: Any) -> Any: ...

