/* Generated from __pmm__.toml version — do not edit. */
#ifndef PYMERGETIC_WASMMOD_EXAMPLES_HELLO_VERHDR_H
#define PYMERGETIC_WASMMOD_EXAMPLES_HELLO_VERHDR_H
#define PYMERGETIC_WASMMOD_EXAMPLES_HELLO_VERSION "0.1.0"
#endif
