"""Stubs for the bridge.wasm pack."""

from typing import Any

def rs_square(x: int) -> int: ...
def rs_add3(a: int, b: int, c: int) -> int: ...
def rs_via_hello() -> int: ...
def rs_via_host(x: int) -> int: ...
def rs_via_i64(x: int) -> int: ...
def rs_via_f32(x: float) -> float: ...
def rs_via_f64(x: float) -> float: ...
def rs_scale_add_f64(x: float, s: float, b: float) -> float: ...
def rs_via_host_i64(x: int) -> int: ...
def rs_via_host_f32(x: float) -> float: ...
def rs_via_host_f64(x: float) -> float: ...
def rs_via_mixed_i64(x: int) -> int: ...
def rs_via_buf() -> int: ...
def rs_via_mem() -> int: ...
def rs_via_handle(handle: int) -> int: ...

def via_rs(x: int) -> int: ...
def via_hello() -> int: ...
def via_mixed() -> int: ...
def via_mixed_i64(x: int) -> int: ...
def via_host(x: int) -> int: ...
def via_host0() -> int: ...
def via_buf() -> int: ...
def via_mem() -> int: ...
def via_handle(handle: int) -> int: ...
def via_mem_out(cookie: int) -> int: ...
def via_i64(x: int) -> int: ...
def via_f32(x: float) -> float: ...
def via_f64(x: float) -> float: ...
def add3(a: int, b: int, c: int) -> int: ...
def scale_add_f64(x: float, s: float, b: float) -> float: ...
def via_host_i64(x: int) -> int: ...
def via_host_f32(x: float) -> float: ...
def via_host_f64(x: float) -> float: ...
def matrix(x: int) -> int: ...
def matrix_rich(x: int) -> int: ...
def ping() -> str: ...
def via_native(x: int) -> int: ...
def via_native_rich(x: int) -> int: ...
def via_peer_hello() -> int: ...
def via_peer_mixed_i64(x: int) -> int: ...
def via_py_self() -> str: ...
def via_peer_util() -> str: ...
def via_host_api(x: int) -> int: ...
def via_c_self(x: int) -> int: ...
def rs_via_square(x: int) -> int: ...
def rs_via_add3(x: int) -> int: ...

__pack__: Any
