/* DO NOT EDIT — generated by `pymergetic.util.gen` (live registry introspection).
 * Source of truth: pm_wasmmod_registry_* after PM_MOD_EXPORT_* / PM_MOD_EXPORT_RS! registration.
 */
#ifndef PYMERGETIC_WASMMOD_API_EXPORT_H
#define PYMERGETIC_WASMMOD_API_EXPORT_H

#include <stddef.h>
#include <stdint.h>

#include "pymergetic/wasmmod/registry/__types__.h"

#ifdef __cplusplus
extern "C" {
#endif

int32_t pm_wasmmod_api_call0_i32(const uint8_t *, uint32_t, const uint8_t *, uint32_t, int32_t *);

int32_t pm_wasmmod_api_connect(const uint8_t *, uint32_t, const uint8_t *, uint32_t, pm_wasmmod_registry_fn_t *);

int32_t pm_wasmmod_api_call2_i32(const uint8_t *, uint32_t, const uint8_t *, uint32_t, int32_t, int32_t, int32_t *);

#ifdef __cplusplus
}
#endif

#endif /* PYMERGETIC_WASMMOD_API_EXPORT_H */
