# DO NOT EDIT — generated by `pymergetic.util.gen` (live µPy import).
# pymergetic.wasmmod.api

from typing import Any

def call0_i32(*args: Any, **kwargs: Any) -> Any: ...

def call2_i32(*args: Any, **kwargs: Any) -> Any: ...

def connect(*args: Any, **kwargs: Any) -> Any: ...

