/*
 * pymergetic.util.gen CPython face.
 * VFS ops = POSIX fopen (CPython has no µPy VFS). Same C ABI as µPy modgen.c.
 */

#define PY_SSIZE_T_CLEAN
#include <Python.h>

#include "ports/cpython/modgen.h"

#include <errno.h>
#include <stdio.h>
#include <string.h>
#include <sys/stat.h>

#include "ports/cpython/importhook.h"
#include "pymergetic/util/gen/__exports__.h"
#include "pymergetic/wasmmod/pack/alloc.h"

static uint8_t *g_pyi;
static uint32_t g_pyi_len;

/* Reserved words that cannot be a def name in valid Python. Mirrors
 * is_python_keyword in util/gen/__impl__.rs — keep both in sync. */
static int pyi_name_is_keyword(const char *s) {
    static const char *const kws[] = {
        "False", "None", "True", "and", "as", "assert", "async", "await",
        "break", "class", "continue", "def", "del", "elif", "else", "except",
        "finally", "for", "from", "global", "if", "import", "in", "is",
        "lambda", "nonlocal", "not", "or", "pass", "raise", "return", "try",
        "while", "with", "yield", NULL
    };
    const char *const *k;
    for (k = kws; *k != NULL; k++) {
        if (strcmp(*k, s) == 0) return 1;
    }
    return 0;
}

static void gen_install_py_face(void);

static int32_t gen_py_face_provider(void *ctx, const uint8_t *fqn, uint32_t fqn_len, uint8_t *buf,
    uint32_t *inout_len) {
    (void)ctx;
    if (fqn == NULL || fqn_len == 0 || inout_len == NULL) {
        return -1;
    }
    if (buf == NULL) {
        MICROPY_WASM_FREE(g_pyi);
        g_pyi = NULL;
        g_pyi_len = 0;

        char name[256];
        if (fqn_len >= sizeof(name)) {
            return 0;
        }
        memcpy(name, fqn, fqn_len);
        name[fqn_len] = '\0';

        PyObject *mod = PyImport_ImportModule(name);
        if (mod == NULL) {
            PyErr_Clear();
            return 0;
        }
        PyObject *dict = PyModule_GetDict(mod);
        if (dict == NULL) {
            Py_DECREF(mod);
            PyErr_Clear();
            return 0;
        }

        PyObject *parts = PyBytes_FromFormat(
            "# DO NOT EDIT — generated by `pymergetic.util.gen` (live CPython import).\n"
            "# %s\n\nfrom typing import Any\n\n",
            name);
        if (parts == NULL) {
            Py_DECREF(mod);
            PyErr_Clear();
            return 0;
        }
        int any = 0;
        PyObject *key, *value;
        Py_ssize_t pos = 0;
        PyObject *kw_names = PyList_New(0);
        if (kw_names == NULL) {
            Py_DECREF(parts);
            Py_DECREF(mod);
            PyErr_Clear();
            return 0;
        }
        while (PyDict_Next(dict, &pos, &key, &value)) {
            if (!PyUnicode_Check(key)) {
                continue;
            }
            const char *attr = PyUnicode_AsUTF8(key);
            if (attr == NULL || attr[0] == '_') {
                continue;
            }
            if (!PyCallable_Check(value)) {
                continue;
            }
            /* A keyword can never be a def name or an annotation target;
             * collect it and expose it via module __getattr__ below. */
            PyObject *line;
            if (pyi_name_is_keyword(attr)) {
                PyObject *kwname = PyUnicode_FromString(attr);
                if (kwname == NULL || PyList_Append(kw_names, kwname) != 0) {
                    Py_XDECREF(kwname);
                    Py_DECREF(kw_names);
                    Py_DECREF(parts);
                    Py_DECREF(mod);
                    PyErr_Clear();
                    return 0;
                }
                Py_DECREF(kwname);
                any = 1;
                continue;
            }
            line = PyBytes_FromFormat("def %s(*args: Any, **kwargs: Any) -> Any: ...\n\n",
                attr);
            if (line == NULL) {
                Py_DECREF(kw_names);
                Py_DECREF(parts);
                Py_DECREF(mod);
                PyErr_Clear();
                return 0;
            }
            PyBytes_ConcatAndDel(&parts, line);
            if (parts == NULL) {
                Py_DECREF(kw_names);
                Py_DECREF(mod);
                PyErr_Clear();
                return 0;
            }
            any = 1;
        }
        Py_DECREF(mod);
        if (!any) {
            Py_DECREF(kw_names);
            Py_DECREF(parts);
            return 0;
        }
        if (PyList_Size(kw_names) > 0) {
            PyObject *line = PyBytes_FromString(
                "from typing import Callable, Literal\n\n");
            if (line != NULL) {
                PyBytes_ConcatAndDel(&parts, line);
            }
            Py_ssize_t nkw = PyList_Size(kw_names);
            for (Py_ssize_t i = 0; i < nkw; i++) {
                const char *kw = PyUnicode_AsUTF8(PyList_GetItem(kw_names, i));
                if (kw == NULL) {
                    PyErr_Clear();
                    continue;
                }
                PyObject *kline = PyBytes_FromFormat(
                    "def __getattr__(name: Literal[\"%s\"]) -> Callable[..., Any]: ...\n\n",
                    kw);
                if (kline == NULL) {
                    PyErr_Clear();
                    continue;
                }
                PyBytes_ConcatAndDel(&parts, kline);
                if (parts == NULL) {
                    Py_DECREF(kw_names);
                    PyErr_Clear();
                    return 0;
                }
            }
        }
        Py_DECREF(kw_names);
        char *raw = NULL;
        Py_ssize_t n = 0;
        if (PyBytes_AsStringAndSize(parts, &raw, &n) != 0 || n <= 0) {
            Py_DECREF(parts);
            PyErr_Clear();
            return 0;
        }
        g_pyi = MICROPY_WASM_MALLOC((size_t)n);
        if (g_pyi == NULL) {
            Py_DECREF(parts);
            return -1;
        }
        memcpy(g_pyi, raw, (size_t)n);
        g_pyi_len = (uint32_t)n;
        Py_DECREF(parts);
        *inout_len = g_pyi_len;
        return 1;
    }
    uint32_t n = *inout_len;
    if (n > g_pyi_len) {
        n = g_pyi_len;
    }
    if (n > 0 && g_pyi != NULL) {
        memcpy(buf, g_pyi, n);
    }
    *inout_len = n;
    return 1;
}

static void mkdir_p_parent(const char *path) {
    char tmp[1536];
    size_t n = strlen(path);
    if (n == 0 || n >= sizeof(tmp)) {
        return;
    }
    memcpy(tmp, path, n + 1);
    for (size_t i = 1; i < n; ++i) {
        if (tmp[i] != '/') {
            continue;
        }
        tmp[i] = '\0';
        if (mkdir(tmp, 0755) != 0 && errno != EEXIST) {
            tmp[i] = '/';
            return;
        }
        tmp[i] = '/';
    }
}

static int32_t gen_vfs_read(void *ctx, const uint8_t *path, uint32_t path_len, uint8_t *buf,
    uint32_t *inout_len) {
    (void)ctx;
    if (path == NULL || path_len == 0 || inout_len == NULL) {
        return -1;
    }
    char p[1536];
    if (path_len >= sizeof(p)) {
        return -1;
    }
    memcpy(p, path, path_len);
    p[path_len] = '\0';
    FILE *f = fopen(p, "rb");
    if (f == NULL) {
        return 0;
    }
    if (fseek(f, 0, SEEK_END) != 0) {
        fclose(f);
        return -1;
    }
    long sz = ftell(f);
    if (sz < 0) {
        fclose(f);
        return -1;
    }
    if (buf == NULL) {
        *inout_len = (uint32_t)sz;
        fclose(f);
        return 1;
    }
    if (fseek(f, 0, SEEK_SET) != 0) {
        fclose(f);
        return -1;
    }
    uint32_t n = *inout_len;
    if ((long)n > sz) {
        n = (uint32_t)sz;
    }
    size_t got = n > 0 ? fread(buf, 1, n, f) : 0;
    fclose(f);
    *inout_len = (uint32_t)got;
    return 1;
}

static int32_t gen_vfs_write(void *ctx, const uint8_t *path, uint32_t path_len, const uint8_t *data,
    uint32_t data_len) {
    (void)ctx;
    if (path == NULL || path_len == 0) {
        return -1;
    }
    char p[1536];
    if (path_len >= sizeof(p)) {
        return -1;
    }
    memcpy(p, path, path_len);
    p[path_len] = '\0';
    mkdir_p_parent(p);
    FILE *f = fopen(p, "wb");
    if (f == NULL) {
        return -1;
    }
    size_t n = data_len > 0 ? fwrite(data, 1, data_len, f) : 0;
    int err = ferror(f);
    fclose(f);
    if (err || n != data_len) {
        return -1;
    }
    return 0;
}

static void gen_install_py_face(void) {
    pm_util_gen_set_py_face_provider(gen_py_face_provider, NULL);
}

PyObject *pm_cpy_gen_run(PyObject *self, PyObject *args) {
    (void)self;
    const char *root = ".";
    int check = 0;
    if (!PyArg_ParseTuple(args, "|sp", &root, &check)) {
        return NULL;
    }
    if (pm_cpy_ensure_inited() != 0) {
        return NULL;
    }
    gen_install_py_face();
    int32_t rc = pm_util_gen_run((const uint8_t *)root, (uint32_t)strlen(root), check);
    return PyLong_FromLong(rc);
}

PyObject *pm_cpy_gen_run_vfs(PyObject *self, PyObject *args) {
    (void)self;
    const char *dir;
    const char *fqn;
    int check = 0;
    if (!PyArg_ParseTuple(args, "ss|p", &dir, &fqn, &check)) {
        return NULL;
    }
    if (pm_cpy_ensure_inited() != 0) {
        return NULL;
    }
    gen_install_py_face();
    pm_util_gen_vfs_ops_t ops = { .read = gen_vfs_read, .write = gen_vfs_write };
    int32_t rc = pm_util_gen_run_vfs((const uint8_t *)dir, (uint32_t)strlen(dir),
        (const uint8_t *)fqn, (uint32_t)strlen(fqn), check, ops, NULL);
    return PyLong_FromLong(rc);
}

PyObject *pm_cpy_gen_diff(PyObject *self, PyObject *args) {
    (void)self;
    const char *fqn;
    const char *h = NULL;
    Py_ssize_t h_len = 0;
    const char *rs = NULL;
    Py_ssize_t rs_len = 0;
    const char *pyi = NULL;
    Py_ssize_t pyi_len = 0;
    if (!PyArg_ParseTuple(args, "s|z#z#z#", &fqn, &h, &h_len, &rs, &rs_len, &pyi, &pyi_len)) {
        return NULL;
    }
    if (pm_cpy_ensure_inited() != 0) {
        return NULL;
    }
    gen_install_py_face();
    int32_t rc = pm_util_gen_diff_included((const uint8_t *)fqn, (uint32_t)strlen(fqn),
        (const uint8_t *)h, (uint32_t)h_len, (const uint8_t *)rs, (uint32_t)rs_len,
        (const uint8_t *)pyi, (uint32_t)pyi_len);
    return PyLong_FromLong(rc);
}

static PyMethodDef gen_methods[] = {
    {"run", pm_cpy_gen_run, METH_VARARGS, NULL},
    {"run_vfs", pm_cpy_gen_run_vfs, METH_VARARGS, NULL},
    {"diff", pm_cpy_gen_diff, METH_VARARGS, NULL},
    {NULL, NULL, 0, NULL},
};

static struct PyModuleDef gen_module = {
    PyModuleDef_HEAD_INIT,
    .m_name = "pymergetic.util.gen",
    .m_doc = "wasmmod facegen (VfsSink / diff / optional FsSink)",
    .m_size = -1,
    .m_methods = gen_methods,
};

int pm_cpy_install_gen(void) {
    PyObject *sysm = PyImport_GetModuleDict();
    if (PyDict_GetItemString(sysm, "pymergetic.util.gen") != NULL) {
        return 0;
    }
    PyObject *gen = PyModule_Create(&gen_module);
    if (gen == NULL) {
        return -1;
    }
    if (PyDict_SetItemString(sysm, "pymergetic.util.gen", gen) != 0) {
        Py_DECREF(gen);
        return -1;
    }
    PyObject *util = PyImport_ImportModule("pymergetic.util");
    if (util != NULL) {
        if (PyObject_SetAttrString(util, "gen", gen) != 0) {
            PyErr_Clear();
        }
        Py_DECREF(util);
    } else {
        PyErr_Clear();
    }
    Py_DECREF(gen); /* dict owns */
    return 0;
}
