"""Stubs for the MicroPython `wasm` builtin (MICROPY_PY_WASM)."""

from typing import Any, Callable, Optional

VERIFY: int  # compile-time MICROPY_WASM_VERIFY (0/1/2)
AOT: int
JIT: int
FAST_JIT: int
MODE: int  # WAMR RunningMode: 1=Interp 2=Fast_JIT 3=LLVM_JIT 4=Multi_Tier
path: list[str]
arch: list[str]  # AOT only: ".<arch>" infix on .aot (e.g. "thumbv7em"); .wasm stays plain

def verify(enabled: bool = ...) -> Any:
    """Session verify gate for all loads (VFS + HTTP). verify()→bool; verify(False) sets."""
    ...

def load(data: str | bytes) -> Any: ...
def load_pack(path: str | bytes, name: Optional[str] = None) -> Any: ...
def unload(name: str) -> None: ...
def import_wasm(name: str) -> Any: ...
def install_hook(url: Optional[str] = None) -> None: ...
def uninstall_hook() -> None: ...
def host_set(slot: int, callable: Callable[..., Any] | None) -> None: ...
def host_get(slot: int) -> Any: ...
def host_clear(slot: Optional[int] = None) -> None: ...
# Present only when built with MICROPY_PY_WASM_MATRIX=1 (call-matrix smoke).
def host_c_triple(x: int) -> int: ...
def host_rs_triple(x: int) -> int: ...
def c_call(pack: str, func: str, *args: int) -> int: ...
def c_call_attr(module: str, attr: str, arg: Optional[int] = None) -> Any: ...
def rs_call(pack: str, func: str, *args: int) -> int: ...
def rs_call_attr(module: str, attr: str, arg: Optional[int] = None) -> Any: ...

def add_trust(key: bytes) -> None: ...
def trust_clear() -> None: ...
def trust_count() -> int: ...

# Host mem cookies (opaque i32; durable host heap)
def mem_alloc(size_or_data: int | bytes) -> int: ...
def mem_free(cookie: int) -> None: ...
def mem_get(cookie: int) -> bytes: ...
def mem_set(cookie: int, data: bytes) -> None: ...
def mem_clear() -> None: ...

# Python object handles (opaque i32; GC-rooted)
def handle_register(obj: Any) -> int: ...
def handle_resolve(handle: int) -> Any: ...
def handle_free(handle: int) -> None: ...
def handle_clear() -> None: ...
