"""Stubs for the hello.wasm pack (native + embedded py/)."""

from typing import Any

def hello() -> int: ...
def add(a: int, b: int) -> int: ...
def greet() -> str: ...
def answer() -> int: ...

__wasm__: Any
