"""Stubs for the hello.wasm pack (native + embedded src/)."""

from typing import Any

def hello() -> int: ...
def add(a: int, b: int) -> int: ...
def greet() -> str: ...
def answer() -> int: ...

__pack__: Any
# Smoke tests may attach host callables for guest call0_py.
_elf_abs: Any
