#!/bin/sh
# Card faces — __exports__.h, __exports__.rs, __init__.pyi — are generated by
# pymergetic.util.gen from the live registry, and each card gitignores its own.
# The generator is the source of truth, so the build runs it: a fresh clone
# compiles without anyone remembering `make gen`.
#
#   genfaces.sh [--force] [ROOT ...]
#
# This crate's src/ and examples/ are always scanned. A downstream card tree —
# a kernel's card tree, say — names itself as a ROOT argument; wasmmod keeps no
# who depends on it. The stamp is keyed on the root set, so a wasmmod-only build
# never convinces a later downstream build that its faces are already there.
#
# Progress goes to stderr; the make fragment that calls this reads stdout.

set -eu

here=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
wasmmod=$(dirname "$here")

force=0
[ "${1:-}" = --force ] && {
    force=1
    shift
}

roots=""
for r in "$wasmmod/src" "$wasmmod/examples" "$@"; do
    [ -d "$r" ] && roots="$roots $r"
done
[ -n "$roots" ] || {
    echo "genfaces.sh: no card tree under $wasmmod" >&2
    exit 1
}

key=$(printf '%s' "$roots" | cksum | cut -d' ' -f1)
stamp="$wasmmod/build/genfaces.$key.stamp"

# Only the files the generator actually reads count as staleness: manifests and
# muscle sources. Its own output (__exports__.rs, __init__.pyi, __version__.h)
# must not retrigger it, and neither may anything a build drops in the tree.
stale() {
    # shellcheck disable=SC2086
    find $roots \( -name build -o -name target -o -name .pm \) -prune -o \
        \( -name '__pmm__.toml' -o -name '__impl__.c' -o -name '__impl__.rs' \
        -o -name '__crypto__.c' -o -name '__types__.h' -o -name '__tests__.c' \
        -o -name '__init__.py' -o -name '__init__.c' -o -name '__init__.rs' \) \
        -newer "$stamp" -print -quit 2>/dev/null
}

if [ "$force" -eq 0 ] && [ -f "$stamp" ] && [ -z "$(stale)" ]; then
    exit 0
fi

echo "GEN  card faces (pymergetic.util.gen)" >&2
# shellcheck disable=SC2086
(cd "$wasmmod" && cargo run --quiet --features gen --bin wasmmod-gen -- $roots) >&2

mkdir -p "$(dirname "$stamp")"
touch "$stamp"
