/* DO NOT EDIT — generated by `pymergetic.util.gen` (live registry introspection).
 * Source of truth: pm_wasmmod_registry_* after PM_MOD_EXPORT_* / PM_MOD_EXPORT_RS! registration.
 */
#ifndef PYMERGETIC_UTIL_MTAR_EXPORT_H
#define PYMERGETIC_UTIL_MTAR_EXPORT_H

#include <stddef.h>
#include <stdint.h>

#include "pymergetic/util/mtar/__types__.h"

#ifdef __cplusplus
extern "C" {
#endif

int32_t pm_util_mtar_first(const uint8_t *, uint32_t, MtarEntry *);

int32_t pm_util_mtar_next(const uint8_t *, uint32_t, const MtarEntry *, MtarEntry *);

#ifdef __cplusplus
}
#endif

#endif /* PYMERGETIC_UTIL_MTAR_EXPORT_H */
