//! DO NOT EDIT — generated by `pymergetic.util.gen` (live registry introspection).

#![allow(non_camel_case_types)]

#[repr(C)]
pub struct MtarEntry {
    _opaque: [u8; 0],
}

unsafe extern "C" {
    pub fn pm_util_mtar_first(a0: *const u8, a1: u32, a2: *mut MtarEntry) -> i32;
    pub fn pm_util_mtar_next(a0: *const u8, a1: u32, a2: *const MtarEntry, a3: *mut MtarEntry) -> i32;
}
