# DO NOT EDIT — generated by `pymergetic.util.gen` (live µPy import).
# pymergetic.util.mtar

from typing import Any

def first(*args: Any, **kwargs: Any) -> Any: ...

def next(*args: Any, **kwargs: Any) -> Any: ...

